<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comment', 'doctrine');

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $request_id
 * @property integer $theme_id
 * @property string $description
 * @property RequestTheme $RequestTheme
 * @property RequestTheme $RequestTheme_2
 * 
 * @method integer      getId()             Returns the current record's "id" value
 * @method integer      getRequestId()      Returns the current record's "request_id" value
 * @method integer      getThemeId()        Returns the current record's "theme_id" value
 * @method string       getDescription()    Returns the current record's "description" value
 * @method RequestTheme getRequestTheme()   Returns the current record's "RequestTheme" value
 * @method RequestTheme getRequestTheme2()  Returns the current record's "RequestTheme_2" value
 * @method Comment      setId()             Sets the current record's "id" value
 * @method Comment      setRequestId()      Sets the current record's "request_id" value
 * @method Comment      setThemeId()        Sets the current record's "theme_id" value
 * @method Comment      setDescription()    Sets the current record's "description" value
 * @method Comment      setRequestTheme()   Sets the current record's "RequestTheme" value
 * @method Comment      setRequestTheme2()  Sets the current record's "RequestTheme_2" value
 * 
 * @package    aeurus
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('request_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('theme_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RequestTheme', array(
             'local' => 'request_id',
             'foreign' => 'request_id'));

        $this->hasOne('RequestTheme as RequestTheme_2', array(
             'local' => 'theme_id',
             'foreign' => 'theme_id'));
    }
}