<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RequestTheme', 'doctrine');

/**
 * BaseRequestTheme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $request_id
 * @property integer $theme_id
 * @property Request $Request
 * @property Theme $Theme
 * @property Doctrine_Collection $Comment
 * @property Doctrine_Collection $Comment_2
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getRequestId()  Returns the current record's "request_id" value
 * @method integer             getThemeId()    Returns the current record's "theme_id" value
 * @method Request             getRequest()    Returns the current record's "Request" value
 * @method Theme               getTheme()      Returns the current record's "Theme" value
 * @method Doctrine_Collection getComment()    Returns the current record's "Comment" collection
 * @method Doctrine_Collection getComment2()   Returns the current record's "Comment_2" collection
 * @method RequestTheme        setId()         Sets the current record's "id" value
 * @method RequestTheme        setRequestId()  Sets the current record's "request_id" value
 * @method RequestTheme        setThemeId()    Sets the current record's "theme_id" value
 * @method RequestTheme        setRequest()    Sets the current record's "Request" value
 * @method RequestTheme        setTheme()      Sets the current record's "Theme" value
 * @method RequestTheme        setComment()    Sets the current record's "Comment" collection
 * @method RequestTheme        setComment2()   Sets the current record's "Comment_2" collection
 * 
 * @package    aeurus
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequestTheme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('request_theme');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('request_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('theme_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Request', array(
             'local' => 'request_id',
             'foreign' => 'id'));

        $this->hasOne('Theme', array(
             'local' => 'theme_id',
             'foreign' => 'id'));

        $this->hasMany('Comment', array(
             'local' => 'request_id',
             'foreign' => 'request_id'));

        $this->hasMany('Comment as Comment_2', array(
             'local' => 'theme_id',
             'foreign' => 'theme_id'));
    }
}