<?php

/**
 * RequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Request');
    }
}