<?php

/**
 * RequestThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequestThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequestThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RequestTheme');
    }
}