<?php

/**
 * ThemeTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThemeTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThemeTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ThemeTag');
    }
}